### ISSUE TITLE
slice bounds out of range errors reported

### ISSUE THREAD

**Issue by bignis** [buger/gor#203]
Running Gor v0.10.1  on Oracle Linux, I notice errors being reported.

I ran Gor with
sudo ./gor -verbose --input-raw :8080 --output-http http://10.184.42.47:8080

With output like

[DEBUG][PID 16661][1441376136828395724][1441376136828.395752ms] Listening for traffic on: :8080
[DEBUG][PID 16661][1441376160273755632][23445.359908ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160442011967][168.256335ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160442285169][0.273202ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160442468339][0.183170ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160442638564][0.170225ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160442841823][0.203259ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 16661][1441376160482126073][39.284250ms] [HTTPClient] Connecting: http://10.184.42.47:8080
2015/09/04 14:16:10 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 14:16:10 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

I did notice that even though these PANICs occur, traffic still gets sent to the other machine successfully.  Also, these errors pop up even though I'm not actively generating traffic on the source machine (i.e. they happen 'asynchronously')

Not sure what other info I can provide, but let me know if there's more details that would be helpful.

**Comment by buger** [comment]
Thanks for the report! I added additional debug, here is the binaries: 
https://www.dropbox.com/s/xn3izhkfd8bvfh3/gor_listener_debug_x64.tar.gz?dl=1
https://www.dropbox.com/s/4cab8x09lircsto/gor_listener_debug_x86.tar.gz?dl=1

**Comment by bignis** [comment]
[DEBUG][PID 18493][1441391694172780614][0.180101ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 18493][1441391694209982775][37.202161ms] [HTTPClient] Connecting: http://10.184.42.47:8080
[DEBUG][PID 18493][1441391694210408473][0.425698ms] [HTTPClient] Connecting: http://10.184.42.47:8080
2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53173
Dest port:8080
Sequence:2676762828
Acknowledgment:3502764022
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53176
Dest port:8080
Sequence:2121947064
Acknowledgment:1238727393
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53172
Dest port:8080
Sequence:4147958659
Acknowledgment:1686341719
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53174
Dest port:8080
Sequence:753752993
Acknowledgment:69262000
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53175
Dest port:8080
Sequence:1529783387
Acknowledgment:3324791190
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2015/09/04 18:35:04 PANIC: pkg: runtime error: slice bounds out of range Source port: 53171
Dest port:8080
Sequence:3483659733
Acknowledgment:2371578767
Header len:5
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data: /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x596a94)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x5942f5)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

**Comment by buger** [comment]
Should be fixed, here is binaries (latest master): 
https://www.dropbox.com/s/b7b05k68jj2kv24/gor_small_packet_fix_x64.tar.gz?dl=1
https://www.dropbox.com/s/hgo9fpinevqc87u/gor_small_packet_fix_x86.tar.gz?dl=1

**Comment by bignis** [comment]
no errors with those binaries now

**Comment by benbooth493** [comment]
I'm still seeing the above panic with the latest master branch.
Have you merged in the changes?

**Comment by buger** [comment]
@benbooth493 it was merged, and most likely you are seeing different error. Can you put stracktrace here?

**Comment by benbooth493** [comment]
./gor --input-raw :80 --output-file requests.gor
Version:
2015/09/24 14:38:40 PANIC: pkg: runtime error: slice bounds out of range Source port: 30418
Dest port:80
Sequence:2879873199
Acknowledgment:3407823497
Header len:8
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data:
 /home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5d1cd5)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4732de)
/usr/local/go/src/runtime/panic.go:423 (0x443959)
/usr/local/go/src/runtime/panic.go:18 (0x441e99)
/home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:95 (0x5d02db)
/home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/listener.go:262 (0x5ceffe)
/home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x5cd962)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x475601)

**Comment by yanglo** [comment]
@buger I'm still seeing the above panic with the latest master branch.
Can you see how it happened and fixed it.  Thx
[root@t-service6 go]# /home/bot/go/gospace/src/github.com/buger/gor/gor --input-raw :80 --output-file requests.gor
Version:
2015/10/15 17:03:13 PANIC: pkg: runtime error: slice bounds out of range Source port: 36261
Dest port:80
Sequence:2789526376
Acknowledgment:82121244
Header len:8
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data:
 /home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x567854)
	func.002: log.Println("PANIC: pkg:", r, packet, string(debug.Stack()))
/usr/local/go/src/pkg/runtime/panic.c:248 (0x42456d)
/usr/local/go/src/pkg/runtime/panic.c:552 (0x42501d)
/usr/local/go/src/pkg/runtime/panic.c:472 (0x424d47)
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:95 (0x566270)
	(*TCPMessage).IsMultipart: m := payload[:4]
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:262 (0x56529a)
	(*Listener).processTCPPacket: if !message.IsMultipart() {
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x563e7d)
	(*Listener).listen: t.processTCPPacket(packet)
/usr/local/go/src/pkg/runtime/proc.c:1445 (0x428d90)

2015/10/15 17:04:02 PANIC: pkg: runtime error: slice bounds out of range Source port: 46127
Dest port:80
Sequence:1328514367
Acknowledgment:858768102
Header len:8
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:1
Data:
 /home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x567854)
	func.002: log.Println("PANIC: pkg:", r, packet, string(debug.Stack()))
/usr/local/go/src/pkg/runtime/panic.c:248 (0x42456d)
/usr/local/go/src/pkg/runtime/panic.c:552 (0x42501d)
/usr/local/go/src/pkg/runtime/panic.c:472 (0x424d47)
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:95 (0x566270)
	(*TCPMessage).IsMultipart: m := payload[:4]
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:262 (0x56529a)
	(*Listener).processTCPPacket: if !message.IsMultipart() {
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x563e7d)
	(*Listener).listen: t.processTCPPacket(packet)
/usr/local/go/src/pkg/runtime/proc.c:1445 (0x428d90)

2015/10/15 17:04:06 PANIC: pkg: runtime error: slice bounds out of range Source port: 46143
Dest port:80
Sequence:2678192654
Acknowledgment:3150356660
Header len:8
Flag ns:false
Flag crw:false
Flag ece:false
Flag urg:false
Flag ack:false
Flag psh:false
Flag rst:false
Flag syn:false
Flag fin:false
Window size:0
Checksum:0
Data size:2
Data:
 /home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x567854)
	func.002: log.Println("PANIC: pkg:", r, packet, string(debug.Stack()))
/usr/local/go/src/pkg/runtime/panic.c:248 (0x42456d)
/usr/local/go/src/pkg/runtime/panic.c:552 (0x42501d)
/usr/local/go/src/pkg/runtime/panic.c:472 (0x424d47)
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:95 (0x566270)
	(*TCPMessage).IsMultipart: m := payload[:4]
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:262 (0x56529a)
	(*Listener).processTCPPacket: if !message.IsMultipart() {
/home/bot/go/gospace/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x563e7d)
	(*Listener).listen: t.processTCPPacket(packet)
/usr/local/go/src/pkg/runtime/proc.c:1445 (0x428d90)

**Comment by sergiula** [comment]
I have a problem:

```
~# ./gor --input-raw :80 --output-file requests.gor
Version: 0.10.1
2016/02/25 11:55:40 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)
```
