### ISSUE TITLE
http: panic - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andrewthecoder** [buger/gor#258]
I've been running a Gor instance for the last few months to forward connections from one server to another, and it's proven very helpful (thanks!).

However stdout regularly shows errors / stack traces like the following, and I'd like to get to the bottom of the cause:

```
2016/04/26 07:07:51 http: panic serving 127.0.0.1:39467: runtime error: invalid memory address or nil pointer dereference
goroutine 2105 [running]:
net/http.(*conn).serve.func1(0xc820d54000, 0x7f1602860100, 0xc82002e000)
        /usr/lib/go/src/net/http/server.go:1287 +0xb5
io.(*LimitedReader).Read(0xc8200515c0, 0xc820d50000, 0x2000, 0x2000, 0x2, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:427 +0xb7
io/ioutil.devNull.ReadFrom(0x0, 0x7f16028601d8, 0xc8200515c0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/ioutil/ioutil.go:151 +0x9e
io/ioutil.(*devNull).ReadFrom(0xc82000e400, 0x7f16028601d8, 0xc8200515c0, 0xc820699500, 0x0, 0x0)
        <autogenerated>:9 +0xb1
io.copyBuffer(0x7f160568b248, 0xc82000e400, 0x7f16028601d8, 0xc8200515c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:375 +0x180
io.Copy(0x7f160568b248, 0xc82000e400, 0x7f16028601d8, 0xc8200515c0, 0x5, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:351 +0x64
io.CopyN(0x7f160568b248, 0xc82000e400, 0x0, 0x0, 0x40001, 0xc820d54366, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:327 +0xf7
net/http.(*chunkWriter).writeHeader(0xc820d542e0, 0xc820780800, 0x3, 0x800)
        /usr/lib/go/src/net/http/server.go:901 +0xaf9
net/http.(*chunkWriter).Write(0xc820d542e0, 0xc820780800, 0x3, 0x800, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:261 +0x92
bufio.(*Writer).flush(0xc8207d0500, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:562 +0xe0
bufio.(*Writer).Flush(0xc8207d0500, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:551 +0x2d
net/http.(*response).finishRequest(0xc820d542c0)
        /usr/lib/go/src/net/http/server.go:1153 +0x57
net/http.(*conn).serve(0xc820d54000)
        /usr/lib/go/src/net/http/server.go:1365 +0xc28
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

This has occurred many times, so I have lots of examples of the above if that helps at all.

Unfortunately due to the nature of the recipient server, I'm not even sure if the network request was successfully forwarded in these cases or if the fact that I'm seeing errors means they've been failing some of the time. Certainly plenty of network requests have been succeeding, so it's only occurring occasionally.

This is the command used to start Gor: 
`gor --input-http :5999 --output-http="http://collector.tracepot.com"  --output-file crashes-since-26.01.2016.gor`

I've already looked at #137 which was supposedly resolved a while back, but that may not be relevant.

Any suggestions would be much appreciated, thanks!

**Comment by buger** [comment]
Just released https://github.com/buger/gor/releases/tag/v0.11.0, can you confirm bug still happens?

**Comment by andrewthecoder** [comment]
Thanks for the update! Just rebuilt, will let you know if I see it again. If I haven't seen it one week from now, I'll assume it's fixed and comment as such.

**Comment by buger** [comment]
Thank you!

**Comment by buger** [comment]
@andrewthecoder Just following up! Note that I already released 0.11.2 which contain some of the bugfixes.

**Comment by andrewthecoder** [comment]
Bad news I'm afraid @buger - it's still occurring with a build from tag v0.11.0 (see trace below).

However as you've just mentioned you've released v0.11.2 I'll rebuild from that now and see if it occurs again from now on - thanks!

```
2016/05/04 08:12:29 http: panic serving 127.0.0.1:44917: runtime error: invalid memory address or nil pointer dereference
goroutine 61 [running]:
net/http.(*conn).serve.func1(0xc8201720b0, 0x7f1fac15a0c8, 0xc82002e000)
        /usr/lib/go/src/net/http/server.go:1287 +0xb5
io.(*LimitedReader).Read(0xc82124f2c0, 0xc821a24000, 0x2000, 0x2000, 0x2, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:427 +0xb7
io/ioutil.devNull.ReadFrom(0x0, 0x7f1fac15a1a0, 0xc82124f2c0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/ioutil/ioutil.go:151 +0x9e
io/ioutil.(*devNull).ReadFrom(0xc82000e410, 0x7f1fac15a1a0, 0xc82124f2c0, 0xc821849500, 0x0, 0x0)
        <autogenerated>:9 +0xb1
io.copyBuffer(0x7f1faf5e3248, 0xc82000e410, 0x7f1fac15a1a0, 0xc82124f2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:375 +0x180
io.Copy(0x7f1faf5e3248, 0xc82000e410, 0x7f1fac15a1a0, 0xc82124f2c0, 0x5, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:351 +0x64
io.CopyN(0x7f1faf5e3248, 0xc82000e410, 0x0, 0x0, 0x40001, 0xc8212fe0a6, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:327 +0xf7
net/http.(*chunkWriter).writeHeader(0xc8212fe020, 0xc82189a000, 0x3, 0x800)
        /usr/lib/go/src/net/http/server.go:901 +0xaf9
net/http.(*chunkWriter).Write(0xc8212fe020, 0xc82189a000, 0x3, 0x800, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:261 +0x92
bufio.(*Writer).flush(0xc821300fc0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:562 +0xe0
bufio.(*Writer).Flush(0xc821300fc0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:551 +0x2d
net/http.(*response).finishRequest(0xc8212fe000)
        /usr/lib/go/src/net/http/server.go:1153 +0x57
net/http.(*conn).serve(0xc8201720b0)
        /usr/lib/go/src/net/http/server.go:1365 +0xc28
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by buger** [comment]
Weird issue, i even did not see mention of Gor source files in this backtrace.

**Comment by buger** [comment]
Ah, i think I spotted the trouble. Are you using `--input-HTTP` for a reason? For intercepting traffic, you should use `--input-raw.'.

**Comment by andrewthecoder** [comment]
I honestly never gave it much more thought past "I want to take HTTP requests and forward them to another server", so both input-http and output-http made sense to me, and since it seemed to work I left it alone and moved on!

I'll change it to input-raw now, thanks for pointing this out. Would you expect there to be any difference in functionality, any changes to HTTP headers etc? As mentioned, it's been working fine other than the occasional crash!

**Comment by andrewthecoder** [comment]
I spoke too soon, I get an error when attempting to start it with input-raw:

```
<root@a:~>
zsh/2 1640 # /home/andrew/goprojects/bin/gor --input-http :5999 --output-http="http://collector.tracepot.com" --output-file /home/andrew/ACRA/podfather-crashes-since-04.05.2016.gor
Version:
^C#                                                                                                                                                                                                                                             [Fri 16/05/06 20:05 BST][pts/1][x86_64/linux-gnu/2.6.32-32-pve][5.2]
<root@a:~>
zsh/2 1641 [2] # /home/andrew/goprojects/bin/gor --input-raw :5999 --output-http="http://collector.tracepot.com" --output-file /home/andrew/ACRA/podfather-crashes-since-04.05.2016.gor
Version:
panic: reflect: Call using string as type int

goroutine 1 [running]:
reflect.Value.call(0x800a20, 0x99aec8, 0x13, 0x8bab10, 0x4, 0xc82000a240, 0x3, 0x4, 0x0, 0x0, ...)
        /usr/lib/go/src/reflect/value.go:369 +0x74a
reflect.Value.Call(0x800a20, 0x99aec8, 0x13, 0xc82000a240, 0x3, 0x4, 0x0, 0x0, 0x0)
        /usr/lib/go/src/reflect/value.go:300 +0xb1
main.registerPlugin(0x800a20, 0x99aec8, 0xc82004fe78, 0x3, 0x3)
        /home/andrew/goprojects/src/github.com/buger/gor/plugins.go:50 +0x360
main.InitPlugins()
        /home/andrew/goprojects/src/github.com/buger/gor/plugins.go:88 +0x685
main.main()
        /home/andrew/goprojects/src/github.com/buger/gor/gor.go:38 +0x197

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1
[Fri 16/05/06 20:05 BST][pts/1][x86_64/linux-gnu/2.6.32-32-pve][5.2]
```

**Comment by buger** [comment]
@andrewthecoder are you sure you have 0.11.2? This issue was fixed in this commit https://github.com/buger/gor/commit/5bea65c723deb2f4bed3510a10869f631d67f28c

**Comment by andrewthecoder** [comment]
Pretty sure, I ran go build after checking out the 0.11.2 tag:

```
<andrew@a:~/goprojects/src/github.com/buger/gor>
zsh 1871  (git)-[tags/v0.11.2]-% git status
HEAD detached at v0.11.2
nothing to commit, working directory clean
```

Is there any way to check? I note the "Version" output to stdout on running gor is empty:
```
<andrew@a:~/goprojects/src/github.com/buger/gor>
zsh 1872  (git)-[tags/v0.11.2]-% /home/andrew/goprojects/bin/gor
Version:
```

**Comment by buger** [comment]
Just release new version https://github.com/buger/gor/releases/tag/v0.12.0, i think it should fix your problem for sure.

**Comment by andrewthecoder** [comment]
Just a heads up, I still saw this while using 0.11.2 with input-http:

```
2016/06/02 14:08:09 http: panic serving 127.0.0.1:37114: runtime error: invalid memory address or nil pointer dereference
goroutine 818 [running]:
net/http.(*conn).serve.func1(0xc8218f82c0, 0x7f6890765a40, 0xc82002e020)
        /usr/lib/go/src/net/http/server.go:1287 +0xb5
io.(*LimitedReader).Read(0xc8213081e0, 0xc82192a000, 0x2000, 0x2000, 0x2, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:427 +0xb7
io/ioutil.devNull.ReadFrom(0x0, 0x7f6890765b18, 0xc8213081e0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/ioutil/ioutil.go:151 +0x9e
io/ioutil.(*devNull).ReadFrom(0xc82000e420, 0x7f6890765b18, 0xc8213081e0, 0xc82195d500, 0x0, 0x0)
        <autogenerated>:9 +0xb1
io.copyBuffer(0x7f6894583318, 0xc82000e420, 0x7f6890765b18, 0xc8213081e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:375 +0x180
io.Copy(0x7f6894583318, 0xc82000e420, 0x7f6890765b18, 0xc8213081e0, 0x5, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:351 +0x64
io.CopyN(0x7f6894583318, 0xc82000e420, 0x0, 0x0, 0x40001, 0xc820a40156, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:327 +0xf7
net/http.(*chunkWriter).writeHeader(0xc820a400d0, 0xc82181a000, 0x3, 0x800)
        /usr/lib/go/src/net/http/server.go:901 +0xaf9
net/http.(*chunkWriter).Write(0xc820a400d0, 0xc82181a000, 0x3, 0x800, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:261 +0x92
bufio.(*Writer).flush(0xc82130dc40, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:562 +0xe0
bufio.(*Writer).Flush(0xc82130dc40, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:551 +0x2d
net/http.(*response).finishRequest(0xc820a400b0)
        /usr/lib/go/src/net/http/server.go:1153 +0x57
net/http.(*conn).serve(0xc8218f82c0)
        /usr/lib/go/src/net/http/server.go:1365 +0xc28
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

However I've now upgraded to v0.14.1 and I'm no longer getting a crash when attempting to start in raw mode, so thanks for fixing that!

This is the command I've now used to start up gor - time will tell whether or not we still get any panics!

```
gor --input-raw :5999 --input-raw-track-response --output-file /home/andrew/ACRA/podfather-crashes-since-%Y%m%d.gor --output-file-append --output-http http://collector.tracepot.com
```

**Comment by buger** [comment]
Cool!

**Comment by andrewthecoder** [comment]
Unfortunately I've just received a crash with the latest version:

```
zsh/2 1644 # gor --input-raw :5999 --input-raw-track-response --output-file /home/andrew/ACRA/podfather-crashes-since-%Y%m%d.gor --output-file-append --output-http http://collector.tracepot.com
Version: v0.14.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x4169b9]

goroutine 38 [running]:
panic(0x9758c0, 0xc82000e180)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*FileOutput).flush(0xc820082550)
        /go/src/github.com/buger/gor/output_file.go:211 +0x139
main.NewFileOutput.func1(0xc820082550)
        /go/src/github.com/buger/gor/output_file.go:57 +0x36
created by main.NewFileOutput
        /go/src/github.com/buger/gor/output_file.go:59 +0x96
```

**Comment by buger** [comment]
This is known issue and fixed in master. You can use this binaries:

[gor_DEV-1466094930_mac.tar.gz](https://github.com/buger/gor/files/318911/gor_DEV-1466094930_mac.tar.gz)
[gor_DEV-1466094909_x64.tar.gz](https://github.com/buger/gor/files/318910/gor_DEV-1466094909_x64.tar.gz)
